# Generated by Django 5.1.6 on 2025-02-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
