# Generated by Django 3.1.12 on 2025-02-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20250207_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizsettings',
            name='quiz_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='studentResponse_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='result_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
