# Generated by Django 3.1.12 on 2025-02-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20250207_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
