# Generated by Django 3.1.12 on 2025-02-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20250210_0709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Marks',
            new_name='Mark',
        ),
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
        migrations.RenameModel(
            old_name='QuizSettings',
            new_name='QuizSetting',
        ),
    ]
