# Generated by Django 3.1.12 on 2025-02-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20250210_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='responses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.question'),
        ),
    ]
