# Generated by Django 3.1.12 on 2025-02-13 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20250210_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresponse',
            old_name='responses',
            new_name='question',
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='selected_option',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
