# Generated by Django 3.1.12 on 2025-02-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20250213_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizName',
            fields=[
                ('quizName_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quizName', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='quizTitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.quizname'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='quizTitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizname'),
        ),
    ]
